# Site settings
title: Czar Pino
email: your-email@domain.com
description: Computer Programmer
baseurl: ""
permalink: "/posts/:categories/:title"
url: "https://czarpino.com" # the base hostname & protocol for your site
twitter_username: czarpino
github_username:  czarpino

# Build settings
markdown: kramdown
