# Welcome to Jekyll!
#

# Site settings
title: Czar Pino
description: |
  Symfony Web Developer  
  Linux System Admin  
  Tech Consultant
owner: Czar Pino
first_published: ~
email: inbox@czarpino.com
baseurl: ""
url: "https://www.czarpino.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/czarpino
  github: https://github.com/czarpino
  linkedin-square: https://www.linkedin.com/in/czarpino
  #facebook-official: https://facebook.com/<username>
  google-plus-square: https://plus.google.com/+czarpino
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  stack-overflow: https://stackoverflow.com/users/1349295/czar-pino
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
